import type { Metadata } from 'next';
import './globals.css';
import QueryProvider from './Provider/QueryProvider';
import { SpeedInsights } from '@vercel/speed-insights/next';
import Popup from './ui/common/Popup';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryProvider>
      <html lang="en">
        <body>
          <Popup />
          {children}
          <SpeedInsights />
        </body>
      </html>
    </QueryProvider>
  );
}
