import type { Metadata } from 'next';
import './globals.css';
import { SpeedInsights } from '@vercel/speed-insights/next';
import QueryProvider from '@provider/QueryProvider';
import Popup from '@ui/common/Popup';
import Modal from '@ui/common/Modal';
import SessionWrapper from '@provider/SessionWrapper';
import Drawer from '@ui/common/Drawer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryProvider>
      <SessionWrapper>
        <html lang="en">
          <body>
            <Popup />
            <Modal />
            <Drawer />
            {children}
            <SpeedInsights />
          </body>
        </html>
      </SessionWrapper>
    </QueryProvider>
  );
}
