#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get the current branch name
currentBranch=$(git symbolic-ref --short HEAD)

# Check if the branch is main or dev, and prevent pushing to these branches
if [[ "$currentBranch" == "main" || "$currentBranch" == "dev" ]]; then
  echo "You are not allowed to push directly to the '$currentBranch' branch. Please create a new branch and push your changes there."
  exit 1
fi